services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./prestashop_8.2.1:/app
      - ./certs:/certs
      - ./nginx-lemp/vhost-nginx.conf:/etc/nginx/conf.d/vhost-nginx.conf
    env_file:
      - .env.prod
    networks:
      redelamplemp:
        aliases:
          - a23bernalrc.lan
  phpserver:
    build: php-lemp
    volumes:
      - ./prestashop_8.2.1:/app
      - ./certs:/certs
      - ./php-lemp/www.conf:/etc/php/8.1/fpm/pool.d/www.conf
    networks:
      redelamplemp:

volumes:
  datos:
networks:
  redelamplemp: