<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSXCMXzK\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSXCMXzK/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerSXCMXzK.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerSXCMXzK\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerSXCMXzK\appAppKernelProdContainer([
    'container.build_hash' => 'SXCMXzK',
    'container.build_id' => 'fdf4ba69',
    'container.build_time' => 1742052093,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSXCMXzK');
